/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultorio;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anne Geri
 */
public class ingreso_medico extends javax.swing.JFrame {

   
    public ingreso_medico() {
        initComponents();
        alista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void alista(){
validaCedula.setVisible(false);
validaNombre.setVisible(false);
validaApellido.setVisible(false);
}    
    
    
    
  public int validar(){
    int resultado=0;
    if(medico_cedula.getText().equals("")){
    
        validaCedula.setVisible(true);
        resultado=1;
    }
    else{
    validaCedula.setVisible(false);
    resultado=0;
    
    }
    
    
  if(medico_nombre.getText().equals("")){
    
        validaNombre.setVisible(true);
        
        resultado=1;
    }
  else{
  validaNombre.setVisible(false);
   resultado=0;
  
  }
  
    if(medico_apellido.getText().equals("")){
    
        validaApellido.setVisible(true);
        resultado=1;
    }
    else{
    
    
    validaApellido.setVisible(false);
     resultado=0;
    
    }
    return resultado;
}    
  
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        medico_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        medico_apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        medico_especialidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        medico_registro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        medico_cedula = new javax.swing.JTextField();
        validaCedula = new javax.swing.JLabel();
        validaNombre = new javax.swing.JLabel();
        validaApellido = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Grabar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Ingreso Medico");

        jLabel1.setText("nombre:");

        medico_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medico_nombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Apeliido:");

        medico_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medico_apellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Especialidad:");

        medico_especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medico_especialidadActionPerformed(evt);
            }
        });

        jLabel4.setText("No. Registro");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CONSULTORIO ORTOPEDICO DR. ESTEBAN RIOS");

        jLabel7.setText("Cedula:");

        validaCedula.setForeground(new java.awt.Color(255, 0, 0));
        validaCedula.setText("*");

        validaNombre.setForeground(new java.awt.Color(255, 0, 0));
        validaNombre.setText("*");

        validaApellido.setForeground(new java.awt.Color(255, 0, 0));
        validaApellido.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medico_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medico_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(145, 145, 145)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validaCedula)
                    .addComponent(validaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medico_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(medico_registro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medico_apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validaApellido)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medico_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(validaCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validaNombre)
                    .addComponent(jLabel1)
                    .addComponent(medico_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validaApellido)
                    .addComponent(jLabel2)
                    .addComponent(medico_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medico_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(medico_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(37, 37, 37)
                .addComponent(jButton4)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        medico_cedula.setText("");
        medico_nombre.setText("");
        medico_apellido.setText("");
        medico_especialidad.setText("");
        medico_registro.setText("");
        alista();
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
  //insercion de datos a base de datos
        medico x=new medico(0,"","","",0);
            
        conectar con=new conectar();
        Connection reg= con.conexion();
        String conversion1;
        String conversion2;
        String sql;
       
             
        int y=0;
        y=validar();
        
        if (y==0){
            
        conversion1=medico_cedula.getText(); // convierte text field en entero
        x.cedula=Integer.parseInt(conversion1); //asigna valor a cedula;
        
        x.nombre=medico_nombre.getText();
        
        x.apellido=medico_apellido.getText();
        
        conversion2=medico_registro.getText(); // convierte text field en entero
        x.registro=Integer.parseInt(conversion2); //asigna valor a cedula;
        
        x.especialidad=medico_especialidad.getText();
        
        
        
                
            
        sql="INSERT INTO  medico (cedula,nombre,apellido,tarjetap,especialidad)VALUES(?,?,?,?,?) ";
        try {
            PreparedStatement pst=reg.prepareStatement(sql);
            pst.setInt(1,x.cedula);
            pst.setString(2,x.nombre);
            pst.setString(3,x.apellido);
            pst.setInt(4,x.registro);
            pst.setString(5,x.especialidad);
            
            int n=pst.executeUpdate();
            if(n>0){
             JOptionPane.showMessageDialog(null,"Registrado con exito");
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(ingreso_usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
       else
        {
        JOptionPane.showMessageDialog(null,"hay campos sin diligenciar");
 
        }



    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
     this.dispose();    

    }//GEN-LAST:event_jButton4ActionPerformed

    private void medico_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medico_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medico_apellidoActionPerformed

    private void medico_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medico_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medico_nombreActionPerformed

    private void medico_especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medico_especialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medico_especialidadActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField medico_apellido;
    private javax.swing.JTextField medico_cedula;
    private javax.swing.JTextField medico_especialidad;
    private javax.swing.JTextField medico_nombre;
    private javax.swing.JTextField medico_registro;
    private javax.swing.JLabel validaApellido;
    private javax.swing.JLabel validaCedula;
    private javax.swing.JLabel validaNombre;
    // End of variables declaration//GEN-END:variables
}
